dymensionxyz/dymension

- cmd/dymd/main.go
> added ascii art

- app/app.go
---
For Author:
---
For Reviewer:
--- 
> fix: fixed default prefix back to dym

- readme.md
- scripts/setup_local.sh
---
For Author:
---
For Reviewer:
--- 
> chore: Update README to Include Custom JSON-RPC Ports Usage

- app/app.go
This PR sets the consensus power by 100K DYM instead of 1 DYM
i.e it requires 100K DYM to be bonded
---
For Author:
---
For Reviewer:
--- 
> chroe: updated PowerReduction to 100K DYM

- cmd/dymd/cmd/root.go
- go.mod
- go.sum
---
For Author:
---
For Reviewer:
--- 
> fix: hub not producing snapshots

- cmd/dymd/cmd/inspect.go
- cmd/dymd/cmd/root.go
- go.mod
- go.sum
`dymd inspect` will output the following:
```
Getting rollapps data...
Num of rollapps:  1
Num of state info:  49
Total size of states:  15 kB
Mean: 263 B
Min: 160 B
Max: 813 B
Getting storage on disk...
Size of application.db: 9.7 MB
Size of blockstore.db: 1.4 MB
Size of cs.wal: 2.1 MB
Size of evidence.db: 1.9 kB
Size of snapshots: 1.9 kB
Size of state.db: 1.9 MB
Size of tx_index.db: 1.5 MB
```
---
For Author:
---
For Reviewer:
--- 
> feat: added inspect command

- app/app.go
- app/upgrades/rc/consts.go
- app/upgrades/rc/rc.go
- scripts/setup_local.sh
- scripts/src/genesis_config_commands.sh
* adding DYM token metadata in local setup script
* added the metadata in a UpgradePlan placeholder, to be included in the next upgrade
---
For Author:
---
For Reviewer:
--- 
> fix: bug missing denom metadata

- Makefile
---
For Author:
---
For Reviewer:
--- 
> chore: updated the version tag in Makefile

- .github/workflows/markdown_lint.yml
- osmoutils/sumtree/README.md
- scripts/src/genesis_config_commands.sh
- x/lockup/keeper/lock_test.go
---
For Author:
---
For Reviewer:
--- 
> fix: fixed genesis script

- .github/pull_request_template.md
- .golangci.yml
- contrib/githooks/pre-commit-config.yaml
- osmoutils/sumtree/README.md
- x/lockup/README.md
---
For Author:
---
For Reviewer:
--- 
> fix: fixed pre-commit hooks and linter comments

- scripts/incentives/fund_incentives.sh
- scripts/incentives/incentive_pools_bootstrap.sh
- scripts/incentives/lockup_bootstrap.sh
- scripts/pools/pools_bootstrap.sh
- scripts/src/genesis_config_commands.sh
---
For Author:
---
For Reviewer:
---;
> chore: added lockdrop to the scripts

- docs/static/openapi.yml
- x/rollapp/keeper/msg_server_update_state_test.go
> chore: fix typos

- app/app.go
- simulation/simulation_test.go
- testutil/keeper/sequencer.go
- x/sequencer/keeper/keeper.go
- x/sequencer/keeper/msg_server_create_sequencer.go
- x/sequencer/simulation/create_sequencer.go
---
For Author:
---
For Reviewer:
---;
> chore: remove testing util code from production code

- go.mod
- go.sum
---
For Author:
---
For Reviewer:
---;
> chore: using forked ethermint with recent bugfixes

- app/test_helpers.go
- ibctesting/delayed_ack_test.go
- ibctesting/denom_metadata_test.go
- ibctesting/utils_test.go
- testutil/keeper/delayedack.go
- x/delayedack/hooks.go
- x/delayedack/ibc_middleware.go
- x/delayedack/keeper/keeper.go
- x/delayedack/types/expected_keepers.go
- x/rollapp/abci.go
- Add IBC integration tests, using coordinator from `ibctesting` package
- Wrote multiple UT for delayack and denommetada middlewares
- fixed `x/delayedack/ibc_middleware.go` where packets sent on already finalized height
---
For Author:
---
For Reviewer:
---;
> chore: implement ibc integration tests

- go.mod
- ibctesting/utils_test.go
---
For Author:
---
For Reviewer:
---;
> fix import error

- Dockerfile
Fix Docker build with Goland 1.19.
Linked issue :
https://github.com/dymensionxyz/dymension/issues/401
---
For Author:
---
For Reviewer:
---;
> fix: Update goland compatibility version for Docker

- app/app.go
This reverts commit 61e7d3655910c7c55c149f95ec0ced3a476bd2c7.
---
For Author:
---
For Reviewer:
---;
> Revert "chore: updated PowerReduction to 100K DYM (#289)"

- testutil/keeper/delayedack.go
- x/delayedack/ibc_middleware.go
- x/delayedack/keeper/keeper.go
- x/delayedack/types/expected_keepers.go
- x/denommetadata/ibc_middleware.go
- x/denommetadata/types/expected_keepers.go
---
For Author:
---
For Reviewer:
---;
> chore: skipping middlewares if rollapps disabled

- x/streamer/keeper/invariants.go
- x/streamer/module.go
---
For Author:
---
For Reviewer:
---;
> feat: added invariants for streamer

- x/rollapp/client/cli/tx_create_rollapp.go
---
For Author:
---
For Reviewer:
---;
> chore: support multiple tokens on rollapp registration

- app/upgrades/v2/upgrade.go
---
For Author:
---
For Reviewer:
---;
> fix: Changed v2 upgrade handler to not panic when client status is not found.

- app/app.go
---
For Author:
---
For Reviewer:
---;
> fix: Restored power reduction to 100k 

- app/app.go
- app/upgrades/v2/upgrade.go
---
For Author:
---
For Reviewer:
---;
> chore: hotfix for delegation to single validator to fix halted chain.

- scripts/setup_local.sh
- scripts/src/genesis_config_commands.sh
---
For Author:
---
For Reviewer:
---;
> chore: add p2p storm mitigation to hub genesis

- app/app.go
---
For Author:
---
For Reviewer:
---;
> chore: reverted power reduction to be 1

- go.mod
- go.sum
----
Closes #XXX
I have...
---
For Reviewer:
---
> fix: Add support for making swaps with metamask 

- .github/pull_request_template.md
- go.mod
- go.sum
----
Closes #XXX
I have...
---
For Reviewer:
---
> chore: merge from main 

- app/ante/ante.go
- app/ante/eip712.go
…extension
----
Closes #XXX
I have...
---
For Reviewer:
---
> chore: added back the eip712 legacy handler

- .github/pull_request_template.md
- app/ante/ante.go
- app/ante/eip712.go
- go.mod
- go.sum
- x/rollapp/client/cli/tx_create_rollapp.go
- x/rollapp/client/cli/tx_update_state.go
- x/sequencer/client/cli/tx_create_sequencer.go
- x/streamer/client/cli/tx_create_stream.go
- x/streamer/client/cli/tx_replace_distribution.go
- x/streamer/client/cli/tx_terminate_stream.go
- x/streamer/client/cli/tx_update_distribution.go
----
Closes #XXX
I have...
---
For Reviewer:
---
> chore: rebase from main 

- x/streamer/keeper/distribute.go
- x/streamer/types/stream.go
----
Closes #XXX
I have...
---
For Reviewer:
---
> fix: minor audit fixes

- x/streamer/client/cli/query_test.go
- x/streamer/keeper/distr_info_test.go
- x/streamer/keeper/distribute_test.go
- x/streamer/keeper/genesis_test.go
- x/streamer/keeper/hooks_test.go
- x/streamer/keeper/keeper.go
- x/streamer/keeper/keeper_create_stream_test.go
- x/streamer/keeper/keeper_replace_update_distribution.go
- x/streamer/keeper/keeper_replace_update_distribution_test.go
- x/streamer/keeper/suite_test.go
- x/streamer/proposal_handler.go
- x/streamer/types/distr_info.go
- x/streamer/types/errors.go
fixes
* 8. Inadequate validation of weights in DistrInfo creation
it contains some minor refactor of the createStream API
> fix: audit fixes - total weight validation

- app/ante/handlers.go
- app/params/config.go
- scripts/pools/e2e.sh
- scripts/pools/nativeDenomPoolA.json
- scripts/pools/nativeDenomPoolB.json
- scripts/pools/pools_bootstrap.sh
- scripts/setup_local.sh
- scripts/src/genesis_config_commands.sh
----
Closes #XXX
I have...
---
For Reviewer:
---
> chore: change udym to adym

- readme.md
- scripts/set_params.sh
- scripts/src/genesis_config_commands.sh
---
For Author:
---
For Reviewer:
---;
> Update guide for setting up chain manually

- app/ante/ante.go
- app/ante/eip712.go
- app/ante/handlers.go
- app/params/config.go
- go.mod
- go.sum
- scripts/pools/e2e.sh
- scripts/pools/nativeDenomPoolA.json
- scripts/pools/nativeDenomPoolB.json
- scripts/pools/pools_bootstrap.sh
- scripts/setup_local.sh
- scripts/src/genesis_config_commands.sh
----
Closes #XXX
I have...
---
For Reviewer:
---
> fix: added NewAuthzLimiterDecorator on ante handler

- .gitignore
- go.mod
- go.sum
----
Closes #XXX
I have...
---
For Reviewer:
---
> chore: update osmosis fork to v1.0.0

- go.mod
- go.sum
----
Closes #XXX
I have...
---
For Reviewer:
---
> build(deps) : updated dymension osmo to v1.1.1

- go.mod
- go.sum
----
Closes #XXX
I have...
---
For Reviewer:
---
> build(deps): update osmo to v1.1.2

- go.mod
----
Closes #XXX
I have...
---
For Reviewer:
---
> chore: Add Ledger Nano X and S+ support

- readme.md
- scripts/incentives/fund_incentives.sh
- scripts/incentives/lockup_bootstrap.sh
- scripts/pools/e2e.sh
- scripts/pools/pools_bootstrap.sh
- scripts/setup_local.sh
----
Closes #528
I have...
---
For Reviewer:
---
> fix: add `--gas-prices` flag to bootstrap shell scripts

- readme.md
- scripts/incentives/fund_incentives.sh
- scripts/incentives/lockup_bootstrap.sh
- scripts/pools/e2e.sh
- scripts/pools/pools_bootstrap.sh
- scripts/setup_local.sh
Reverts dymensionxyz/dymension#530 until we update roller with dymension version using `adym`
> Revert "fix: add `--gas-prices` flag to bootstrap shell scripts"

- .github/workflows/release_docker_images.yml
This PR add a workflow for release docker images when have any new tag.
----
Closes #444 
I have...
---
For Reviewer:
---
> CI: Release docker images

- x/delayedack/ibc_middleware.go
- x/denommetadata/ibc_middleware.go
- x/rollapp/types/params.go
- x/streamer/keeper/keeper.go
Fix typos in comments
I have...
---
For Reviewer:
---
> fix: typos in comments

- x/rollapp/keeper/msg_server_update_state_test.go
exsisting -> existing
----
I have...
---
For Reviewer:
---
> chore: update msg_server_update_state_test.go

- ibctesting/delayed_ack_test.go
----
Closes #XXX
I have...
---
For Reviewer:
---
> test: delayed ack timeout test

- .github/workflows/codeql.yml
----
I have...
SDK Checklist
---
For Reviewer:
---
> CI: Add CodeQL

- Makefile
- e2e/README.md
----
I have...
SDK Checklist
---
For Reviewer:
---
> chore: Add docker-build-e2e

- go.sum
- ibctesting/eibc_test.go
- x/delayedack/eibc.go
- x/delayedack/ibc_middleware.go
- x/eibc/genesis_test.go
----
Closes #XXX
I have...
SDK Checklist
For Reviewer:
---;
> fix: disable usage of eIBC combined with PFM 

- .github/workflows/update_docker_images.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> CI: Push image with SHORT-SHA 

- .github/workflows/update_docker_images.yml
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> CI: Update latest tag every new commit to main

- app/ante/handlers.go
- app/ante/ibc_proof_height.go
- x/delayedack/ibc_middleware.go
- x/delayedack/proof_height_ante.go
- x/delayedack/types/proof_height_context.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: added ante handler to pass proofHeight to middleware

- x/rollapp/keeper/msg_server_update_state_test.go
----
With the recent modifications of removing finalized state infos from the BlockHeightToFinalizationQueue, no current tests are checking state infos are finalized correctly. In this PR the TestUpdateState is updated to check that the state infos submitted to the hub get finalized accordingly with the specified dispute period
Closes #649
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: fix grace period finalization test

- app/ante/handlers.go
- x/delayedack/ibc_middleware.go
- x/delayedack/proof_height_ante.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: proof height ante decorator

- proto/dymension/denommetadata/gov_denommetadata.proto
- x/denommetadata/client/cli/tx_create_denommetadata.go
- x/denommetadata/client/cli/tx_update_denommetadata.go
- x/denommetadata/proposal_handler.go
- x/denommetadata/types/gov_denommetadata.pb.go
- x/denommetadata/types/proposal_metadata.go
- x/rollapp/types/tx.pb.go
This PR enables creating governance proposals for adding multiple denom metadata in the same proposal
----
Closes #660 
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: add/update multiple denom metadata in same proposal

- app/app.go
- x/denommetadata/keeper/keeper.go
- x/denommetadata/keeper/keeper_test.go
- x/denommetadata/module.go
- x/denommetadata/proposal_handler.go
- x/denommetadata/types/hooks.go
This PR implements the hooks for the denommetadata module to communicate the denom metadata creation and update events 
----
Closes #659
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: denommetadata module hook for denom creation and update

- Dockerfile.debug
- Makefile
- docker-compose.debug.yml
- readme.md
- scripts/init_config.sh
- scripts/start_node_debug.sh
this PR add Devel debug
run `make docker-run-debug`, add breakpoint, start the debugger. It should pause at breakpoint.
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> feat: Add Devel IDE debug config

- readme.md
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: updated readme.md order

- x/rollapp/keeper/fraud_handler.go
- x/rollapp/keeper/msg_server.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: validate the IBC client on fraud proposal

- app/app.go
- ibctesting/delayed_ack_test.go
- ibctesting/denom_metadata_test.go
- ibctesting/eibc_test.go
- ibctesting/utils_test.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: fix bad test and wiring bug

- app/app.go
- ibctesting/delayed_ack_test.go
- ibctesting/denom_metadata_test.go
- ibctesting/eibc_test.go
- ibctesting/utils_test.go
- x/eibc/module.go
- x/rollapp/module.go
- x/sequencer/module.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: adding invariant wiring

- .github/workflows/test.yml
- x/denommetadata/ibc_middleware.go
- x/denommetadata/ibc_middleware_test.go
----
Closes #706
I have...
SDK Checklist
----;
For Reviewer:
---;
> Chore: remove redundant logs

- x/rollapp/keeper/msg_server_update_state.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> refac: shorten with slices package

- x/rollapp/types/errors.go
----
Closes [#735 ](https://github.com/dymensionxyz/dymension/issues/735)
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix error message typos

- app/ante/handlers.go
- app/app.go
- app/params/config.go
- go.mod
- go.sum
- x/rollapp/keeper/block_height_to_finalization_queue.go
- x/sequencer/keeper/msg_server_unbond.go
- x/streamer/keeper/keeper.go
----
Closes [#743 ](https://github.com/dymensionxyz/dymension/issues/743)
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): update hashicorpgo getter dependency

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: fixed go.mod after merged PR

- CHANGELOG.md
- x/common/types/key_rollapp_packet.go
- x/delayedack/keeper/rollapp_packet.go
- x/eibc/keeper/hooks.go
- x/eibc/keeper/hooks_test.go
- x/eibc/keeper/keeper.go
- x/eibc/keeper/keeper_test.go
- x/eibc/module.go
- x/eibc/types/demand_order.go
Fail fast on more unmarshal errors
----
Closes https://github.com/dymensionxyz/dymension/issues/741
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(delayedack): use must unmarshal

- x/denommetadata/module.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix: fixed export genesis of denommetadata module

- x/sequencer/keeper/hooks_test.go
- x/sequencer/keeper/unbond.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(sequencer): setting proposer to false when forceUnbonding

- x/delayedack/keeper/rollapp_packet.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(delayedack): panic on nil reference when err is returned from updateRollapWithStatus

- .golangci.yml
- contrib/githooks/pre-commit-config.yaml
- x/rollapp/types/key_state_info.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(rollapp): changed state info index to be saved as big indian

- app/ante/handlers.go
----
Closes #755 
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(ante): Add missing ante handler

- app/upgrades/v3/upgrade_test.go
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> Feat: Upgrade handler test

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> build(deps): update osmo dep v15.2.0-dymension-v1.1.3

- CHANGELOG.md
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: missing changelog entry

- x/delayedack/ibc_middleware.go
- x/delayedack/keeper/keeper.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> patch: moved rollapp channel id validation logic 

- ibctesting/delayed_ack_test.go
- ibctesting/denom_metadata_test.go
- ibctesting/eibc_test.go
- ibctesting/rollapp_genesis_token_test.go
- ibctesting/utils_test.go
- x/delayedack/ibc_middleware.go
- x/delayedack/keeper/keeper.go
- x/rollapp/types/errors.go
----
Closes #794 
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(delayedack): fix missing validation of channel id when validating rollapp packet

- app/ante/handlers.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> doc(ante): add a link to explanation of message blocking ante handlers

- ibctesting/utils_test.go
- x/rollapp/keeper/msg_server_create_rollapp.go
- x/rollapp/keeper/msg_server_create_rollapp_test.go
- x/rollapp/types/chain_id.go
This PR is a fix to allow  creating rollapp with the same  EIP155 when forking, but increasing revision number
----
Closes #807 
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix (rollapp): allow creating rollapp same eip155 when forking

- x/delayedack/keeper/fraud.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> refactor(fraud): removed redundancies

- ibctesting/delayed_ack_test.go
- ibctesting/eibc_test.go
- x/delayedack/eibc.go
- x/delayedack/eibc_test.go
- x/delayedack/types/errors.go
- x/delayedack/types/packet_metadata.go
- x/delayedack/types/packet_metadata_test.go
- x/eibc/keeper/demand_order_test.go
- x/eibc/keeper/grpc_query_test.go
- x/eibc/keeper/hooks_test.go
- x/eibc/keeper/invariants_test.go
- x/eibc/keeper/msg_server_test.go
- x/eibc/types/demand_order.go
- x/eibc/types/errors.go
----
Addresses https://github.com/dymensionxyz/dymension/issues/830, https://github.com/dymensionxyz/dymension/issues/830
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(eibc): improve eibc memo error handling

- .github/workflows/release_binary.yml
- .github/workflows/update_docker_images.yml
- .goreleaser.yml
- Makefile
----
Closes #846 
I have tested: https://github.com/decentrio/dymension/releases/tag/v5.0.3
SDK Checklist
----;
For Reviewer:
---;
> [CI]: Generate binary supported both amd and arm

- app/ante/eip712.go
- x/sequencer/keeper/msg_server_create_sequencer_test.go
fix some typos in comments
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: fix some typos in comments

- docs/static/openapi.yml
- ibctesting/eibc_test.go
- readme.md
fix some comments
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: fix some comments

- .github/workflows/e2e_test_upgrade.yml
Have tested here: https://github.com/decentrio/dymension/actions/runs/9122799181/job/25084460701?pr=3
The test failed because we haven't merge it to main, but environment variables were retrieved correctly
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> ci: add workflow for trigger upgrade hub e2e-test

- .githooks/pre-push
- readme.md
- scripts/setup-git-hooks.sh
This PR add pre push hooks and instruction on README
- Golangci-lint
- markdownlint
I have...
SDK Checklist
----;
For Reviewer:
---;
> Feat: Add setup script and git push hooks 

- x/rollapp/types/chain_id.go
- x/sequencer/types/keys.go
fix some function names
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chores(godoc): fix wrong function name in go docs 

- x/eibc/keeper/invariants.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(code standards): deletes unused all invariants func

- proto/dymension/eibc/demand_order.proto
- x/eibc/types/demand_order.pb.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(docs): adds docstrings for demand order proto

- x/streamer/keeper/stream.go
fix function name
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: fix function name

- x/streamer/client/cli/tx_create_stream.go
- x/streamer/client/cli/tx_replace_distribution.go
- x/streamer/client/cli/tx_terminate_stream.go
- x/streamer/client/cli/tx_update_distribution.go
fix some function names
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: fix some function names

- x/delayedack/genesis.go
- x/eibc/genesis.go
- x/eibc/genesis_test.go
- x/rollapp/genesis.go
- x/rollapp/genesis_test.go
- x/sequencer/genesis.go
- x/sequencer/genesis_test.go
- x/sequencer/types/genesis.go
----
Closes #880 
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(rollapp): restore the ability to import rollapp state

- CHANGELOG.md
- x/rollapp/keeper/msg_server_update_state.go
- x/rollapp/types/message_update_state.go
- x/rollapp/types/message_update_state_test.go
----
Closes research/[#317](https://github.com/dymensionxyz/research/issues/317)
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(rollapp): prevent overflow on rollapp state update

- x/eibc/client/cli/tx.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> Feat(eibc-fee): Add cmd update demand order

- x/eibc/client/cli/tx.go
- x/eibc/keeper/msg_server_test.go
- x/eibc/types/tx.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> fix(eibc): fix `update-demand-order` CLI

- go.mod
- go.sum
- x/incentives/client/cli/query_test.go
- x/incentives/keeper/suite_test.go
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;
> chore: remove usage of tendermint deps

- scripts/setup_local.sh
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(setup script): exit local setup if dymd is not installed

- x/sequencer/client/cli/tx.go
----
Closes #1035 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(sequencer): make create sequencer cli command metadata optional

- scripts/setup_local.sh
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore: use SETTLEMENT_EXECUTABLE to remove overlaps

- x/sequencer/keeper/bond_reductions.go
Instead of comparing two `sdk.Coins`, compare the amounts directly as one of the objs will have only one `sdk.Coin` in it
----
Closes #1070
I have...
SDK Checklist
----
For Reviewer:
----
> refactor: change the coins compare in bond reduction to compare the amounts

- x/sequencer/keeper/params.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> Fixed lint in keepers.go

- ibctesting/light_client_test.go
- scripts/src/genesis_config_commands.sh
- testutil/keeper/lightclient.go
- x/lightclient/keeper/canonical_client.go
- x/lightclient/types/expected_keepers.go
- x/lightclient/types/params.go
- x/lightclient/types/params_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(light client): adds query for canonical client for rollapp - use correct client params

- x/rollapp/types/message_update_rollapp.go
- x/rollapp/types/message_update_rollapp_test.go
----
Closes #1170 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollapp): permit initial sequencer to be updated to wildcard

- proto/dymensionxyz/dymension/sponsorship/sponsorship.proto
- x/sponsorship/types/constants.go
- x/sponsorship/types/sponsorship.pb.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> update comment and min default value

- x/sequencer/client/cli/tx.go
----
Closes #1192 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(sequencer): add sequencer decrease bond cli command

- proto/dymensionxyz/dymension/sponsorship/sponsorship.proto
- x/sponsorship/types/sponsorship.pb.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(sponsorship): updated module params comment

- x/rollapp/client/cli/tx_create_rollapp.go
- x/rollapp/types/message_create_rollapp_test.go
- x/rollapp/types/rollapp.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollapp): allow empty values when registering rollapp

- go.mod
- go.sum
- ibctesting/eibc_test.go
- ibctesting/genesis_transfer_test.go
- x/bridgingfee/ibc_module.go
- x/delayedack/ibc_middleware.go
- x/denommetadata/ibc_middleware.go
- x/rollapp/transfergenesis/ibc_module.go
----
Closes #1194 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(ibc): wrap IBC error acknowledgement with an error event

- x/delayedack/client/cli/query.go
- x/dymns/client/cli/query_alias.go
- x/dymns/client/cli/query_buy_order.go
- x/dymns/client/cli/query_dym_name.go
- x/dymns/client/cli/query_params.go
- x/dymns/client/cli/query_resolve.go
- x/dymns/client/cli/query_reverse_resolve.go
- x/dymns/client/cli/query_sell_order.go
- x/eibc/client/cli/query_command_orders.go
- x/eibc/client/cli/query_params.go
- x/lightclient/client/cli/query.go
- x/rollapp/client/cli/query_latest_height.go
- x/rollapp/client/cli/query_latest_state_info_index.go
- x/rollapp/client/cli/query_params.go
- x/rollapp/client/cli/query_rollapp.go
- x/rollapp/client/cli/query_state_info.go
- x/rollapp/client/cli/tx_update_rollapp.go
- x/sequencer/client/cli/query_params.go
- x/sequencer/client/cli/query_sequencer.go
- x/sequencer/client/cli/query_sequencers_by_rollapp.go
- x/sponsorship/client/cli/query.go
----
Closes #1180 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(cli): use proper context for CLI query client

- x/lightclient/README.md
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(doc): add README for canonical light client for operators

- app/ante/handlers.go
- app/keepers/keepers.go
- ibctesting/genesis_transfer_test.go
- ibctesting/transfers_enabled_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(genesistransfer): open the bridge without waiting for a genesis transfer

- Contributing.md
- readme.md
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore: code standards

- x/sponsorship/client/cli/tx.go
----
Closes #1268
I have...
SDK Checklist
----
For Reviewer:
----
> feat(sponsorship): fixed revoke vote CLI

- cmd/dymd/cmd/root.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(mempool): changed to use no-op app mempool by default to fix evm txs signer

- x/rollapp/keeper/liveness.go
- x/rollapp/keeper/liveness_test.go
- x/rollapp/keeper/msg_server_update_state.go
also make sure some random actor cannot set drs version
----
Closes https://github.com/dymensionxyz/dymension/issues/1283
I have...
SDK Checklist
----
For Reviewer:
----
> fix(liveness slash): do not schedule for next block

- x/rollapp/types/message_add_app.go
- x/rollapp/types/message_remove_app.go
- x/rollapp/types/message_update_app.go
- x/rollapp/types/message_update_rollapp.go
- x/rollapp/types/rollapp.go
**What does this PR do?**
Refactor err.Error() 
Replace this:
`errorsmod.Wrap(ErrInvalidCreatorAddress, err.Error())`
To this:
`errors.Join(ErrInvalidCreatorAddress, err)`
----
Closes #1280 
I have...
SDK Checklist
----
For Reviewer:
----
> fix: refactor usage of err.Error()

- app/keepers/keepers.go
- testutil/keeper/iro.go
- x/iro/keeper/create_plan.go
- x/iro/keeper/create_plan_test.go
- x/iro/keeper/keeper.go
- x/iro/types/expected_keepers.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(iro): creating VFC contracts for IRO tokens

- .github/workflows/e2e_test.yml
- .github/workflows/e2e_test_upgrade.yml
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(CI): trigger workflow manually and daily

- .github/workflows/e2e-test-nightly.yml
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(ci): auto trigger e2e-tests nightly

- ibctesting/genesis_bridge_test.go
- x/rollapp/genesisbridge/ibc_module.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(genesis_bridge): json encoding for genesisBridgeData

- app/ante/handlers.go
- go.mod
- go.sum
- ibctesting/transfers_enabled_test.go
- x/rollapp/genesisbridge/ante_decorator.go
- x/rollapp/genesisbridge/expected_keepers.go
- x/rollapp/genesisbridge/ibc_module.go
----
Closes https://github.com/dymensionxyz/dymension/issues/1324
I have...
SDK Checklist
----
For Reviewer:
----
> fix(genesis bridge): get rollapp by light client ID rather than chain ID in transfer enabled check

- x/eibc/keeper/msg_server_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(eibc): add test cases for authorized order fulfillment

- x/eibc/keeper/msg_server_test.go
- x/rollapp/keeper/msg_server_app.go
- x/rollapp/types/message_add_app.go
- x/rollapp/types/message_update_app.go
----
Closes #1350 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollapp): validate order field when validating update app

- ibctesting/utils_test.go
- x/eibc/keeper/msg_server_test.go
- x/rollapp/keeper/msg_server_create_rollapp_test.go
- x/rollapp/keeper/rollapp.go
----
Closes #1239 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollapp): Enforce revision 1 on create rollapps

- x/eibc/keeper/msg_server_test.go
- x/iro/keeper/claim.go
- x/iro/keeper/create_plan.go
- x/iro/keeper/settle.go
- x/iro/keeper/trade.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(iro): use sdk-utils typed events in IRO

- proto/dymensionxyz/dymension/eibc/authz.proto
- x/eibc/client/cli/authz.go
- x/eibc/types/authz.pb.go
- x/eibc/types/fulfill_order_authorization.go
- x/eibc/types/fulfill_order_authorization_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(eibc): filtering per rollapp level when granting authorization

- x/common/types/events.go
- x/common/types/rollapp_packet.go
----
Closes https://github.com/dymensionxyz/dymension/issues/1376
I have...
SDK Checklist
----
For Reviewer:
----
> feat(common): added more attributes to rollapp packet delayed ack event

- ibctesting/utils_test.go
- x/rollapp/genesisbridge/ibc_module.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(rollapp): verify genesis checksum is same in hub and rollapp

- x/lightclient/keeper/hook_listener.go
- x/lightclient/keeper/keeper.go
- x/lightclient/keeper/keeper_test.go
tech debt to make beautiful: https://github.com/dymensionxyz/dymension/issues/1397
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(lightclient): prune signers below on setting canonical

- x/rollapp/keeper/grpc_query_rollapp.go
----
Closes #1187 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollapp): add latest height and latest finalized height to rollapp summary

- x/sequencer/client/cli/tx.go
- x/sequencer/types/msg_update_whitelisted_relayers.go
----
Closes https://github.com/dymensionxyz/dymension-rdk/issues/592
I have...
SDK Checklist
----
For Reviewer:
----
> fix(sequencer): use AccAddress for operator address

- x/delayedack/keeper/finalize.go
- x/eibc/keeper/msg_server.go
- x/eibc/keeper/msg_server_test.go
- x/eibc/types/expected_keepers.go
----
Closes #1432 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(eibc): prevent "finalizable" order due to be fulfilled

- x/rollapp/keeper/msg_server_update_rollapp_test.go
- x/rollapp/keeper/rollapp.go
----
Closes #1428 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollapp): make genesis accounts in genesis info nullable

- x/iro/keeper/trade.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(IRO): no trade allowed before start time

- app/keepers/keepers.go
- x/denommetadata/ibc_middleware.go
- x/denommetadata/ibc_middleware_test.go
- x/denommetadata/keeper/keeper.go
- x/denommetadata/keeper/rollback.go
- x/denommetadata/types/expected_keepers.go
- x/rollapp/keeper/registered_denoms.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(hardfork): clearing rollapp's denom metadata in case of hard fork

- x/iro/keeper/claim.go
Fixes: #1460
Claim denom should be Settle (IBC) denom.
> fix(iro): correct IRO claim denom

- x/rollapp/genesisbridge/genesis_bridge_data_test.go
- x/rollapp/types/genesis_info.go
----
Closes #1473 
I have...
SDK Checklist
----
For Reviewer:
----
> fix: check for duplicates in genesis info accounts

- app/upgrades/v4/rollapp_state_info_next_proposer.go
- app/upgrades/v4/upgrade.go
- app/upgrades/v4/upgrade_test.go
- proto/dymensionxyz/dymension/rollapp/state_info.proto
- x/rollapp/types/state_info.pb.go
----
Closes #1415 
I have...
SDK Checklist
----
For Reviewer:
----
> feat(migrations): next proposer in state info

- x/delayedack/keeper/fraud.go
- x/delayedack/keeper/hooks.go
- x/delayedack/keeper/rollapp_packet.go
- x/delayedack/types/hooks.go
- x/eibc/keeper/hooks.go
- x/eibc/keeper/hooks_test.go
- x/eibc/keeper/keeper.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(delayedack): don't error when deleting packets to prevent endless loop

- x/rollapp/keeper/hard_fork.go
- x/rollapp/keeper/msg_server_update_state.go
- x/rollapp/types/events.go
when handling state update, we write the rollapp object in the end.
currently it overrides any changes done in the hooks
also renamed the HardFork events
> fix(rollapp): fix store issue with hooks

- app/apptesting/gamm.go
- app/keepers/keepers.go
- x/gamm/amm_test.go
- x/rollapp/keeper/keeper.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(app): fix initialization of `transferKeeper` for `x/rollapp`

- x/rollapp/keeper/expected_keepers.go
- x/rollapp/keeper/hard_fork.go
- x/rollapp/keeper/liveness_test.go
- x/rollapp/keeper/msg_server_update_state.go
- x/rollapp/types/events.go
- x/sequencer/keeper/hook_listener.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rotation): complete rotation on `afterStateUpdate` hook

- x/sponsorship/keeper/votes.go
- x/sponsorship/keeper/votes_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(sponsorship): remove sequencer bonded enforcement from rollapp gauge

- app/upgrades/v4/old_rollapps.go
- app/upgrades/v4/upgrade.go
----
Closes #1490 
I have...
SDK Checklist
----
For Reviewer:
----
> feat(rollapp): add nim and mande domain name in migration

- x/iro/keeper/create_plan.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(IRO): updated IRO's metadata name

- Contributing.md
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> docs(contributing): adds section for AI tools

- app/apptesting/test_suite.go
- x/rollapp/keeper/fraud_proposal.go
- x/rollapp/keeper/fraud_proposal_test.go
- x/rollapp/types/rollapp.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollapp): validating rollapp revision on fraud proposal

- x/sponsorship/keeper/staking_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(sponsorship): added tests to verify staking power truncation issue

- app/app.go
> fix(app): fix missing tx encoder

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(gamm): added rewarding of OUT denom in case of DYM-rollapp swaps

- app/keepers/migration.go
- app/upgrades/v4/upgrade.go
- app/upgrades/v4/upgrade_test.go
----
Closes https://github.com/dymensionxyz/dymension/issues/1519
I have...
SDK Checklist
----
For Reviewer:
----
> fix(migration): adds module account perms changes

- go.mod
- go.sum
Since we don't use evm hook this behavior doesn't affect us currently, but in case we will in the future, it will. 
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(deps): upgraded to ethermint which doesn't emit double events on transfer

- x/iro/keeper/iro.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(iro): get tradable plans filter

- x/incentives/keeper/distribute.go
- x/incentives/keeper/gauge_asset.go
- x/incentives/keeper/gauge_rollapp.go
* added event for rollapp gauge distribution
* added `idToGaugeRewards []map[uint64]sdk.Coins // Per-gauge rewards for each recipient indexed by ID`
so events will have the distribution per gauge
event will look like:
```
Event: distribution
- receiver: <address>
- amount: <total_rewards>
- gauge_id_1: <rewards>
- gauge_id_2: <rewards>
- gauge_id_3: <rewards>
...
```
> feat(incentives):  earning events 

- ibctesting/genesis_bridge_test.go
- ibctesting/utils_test.go
- x/iro/keeper/create_plan.go
- x/rollapp/genesisbridge/genesis_bridge_data.go
- x/rollapp/genesisbridge/genesis_transfer.go
- x/rollapp/genesisbridge/ibc_module.go
- x/rollapp/keeper/msg_server_update_rollapp_test.go
- x/rollapp/keeper/rollapp.go
- x/rollapp/types/genesis_info.go
- x/rollapp/types/genesis_info.pb.go
- x/rollapp/types/message_update_rollapp.go
- Genesis accounts semantics is now only dependent on list method call
- Only allow update in unsealed rollapp, and only if specifying non nil genesis accounts wrapper type
----
Closes https://github.com/dymensionxyz/dymension/issues/1547
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollapp): properly disambiguate empty/nil genesis accounts

- x/iro/keeper/invariants.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> Fix IRO invariant: only check sufficiency of IRO tokens after settling

- x/sequencer/keeper/fraud.go
- x/sequencer/keeper/fraud_test.go
- x/sequencer/keeper/proposer.go
----
Closes https://github.com/dymensionxyz/dymension/issues/1580
I have...
SDK Checklist
----
For Reviewer:
----
> fix(sequencer): set unbonded on abrupt removal

- x/rollapp/keeper/msg_server_update_rollapp_test.go
NOTE: feature seems to be working fine, just made sure the test was actually testing
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(rollapp): make the test for updating min bond a bit clearer

- app/keepers/keepers.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(group): increase group metadata maximum length

- Makefile
- docs/static/openapi.yml
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore: makefile swagger from proto generation, regenerate openapi.yml file

- app/keepers/keepers.go
- x/rollapp/keeper/msg_server_create_rollapp_test.go
- x/rollapp/types/message_update_rollapp_test.go
- x/rollapp/types/rollapp.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(group): Increased group policy metadata 

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(deps): updated osmosis dep to fix taker fee event

- x/iro/keeper/invariant_test.go
- x/iro/keeper/settle.go
the claimed amount was off by 1 RA token due to the creation fee
> fix: IRO claimed amount accounting

- x/rollapp/keeper/invariants.go
- x/sequencer/keeper/get_and_set.go
- x/sequencer/keeper/invariants.go
- x/sequencer/keeper/msg_server_kick_proposer_test.go
- x/sequencer/keeper/proposer.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(sequencer): do not allow setting sentinel object

- x/dymns/keeper/hooks.go
- x/dymns/keeper/msg_server_register_alias.go
- x/dymns/keeper/proposal.go
----
Wrong use of `ErrInternal` so I moved to use `ErrUnknown` instead.
I have...
SDK Checklist
----
For Reviewer:
----
> fix(err): replace incorrect usage of `ErrInternal`

- x/lightclient/keeper/keeper.go
- x/sequencer/keeper/msg_server_kick_proposer_test.go
- x/sequencer/keeper/util_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(sequencer, lightclient): do not prevent unbond when canonical client not found

- proto/dymensionxyz/dymension/iro/iro.proto
- x/iro/keeper/create_plan.go
- x/iro/keeper/create_plan_test.go
- x/iro/keeper/settle.go
- x/iro/keeper/settle_test.go
- x/iro/types/params.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> refactor(iro): refacor IRO creation fee

- x/eibc/keeper/keeper_test.go
- x/eibc/keeper/msg_server_test.go
- x/eibc/types/fulfill_order_authorization.go
- x/eibc/types/fulfill_order_authorization_test.go
- x/eibc/types/tx.go
- x/eibc/types/tx_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(eibc): min fee accept check bug fix

- x/sequencer/keeper/grpc_query_sequencers_by_rollapp.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(sequencer): do not return sentinel values

- x/iro/keeper/invariant_test.go
- x/iro/keeper/invariants.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(iro, invariant): remove non invariant

- app/upgrades/v4/upgrade.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(migration): changed default values for incentive creation to protect against dos

- x/sequencer/types/codec.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(sequencer): register PunishSequencerProposal type

- x/rollapp/keeper/msg_server_update_rollapp_test.go
- x/rollapp/types/rollapp.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollapp): metadata URL validation

- app/upgrades/v4/upgrade.go
- app/upgrades/v4/upgrade_test.go
----
Closes #1631 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(gamm): add migration for correcting gamm pools denom metadata

- .github/workflows/changelog.yml
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(CI): allow to run change log manually

- x/eibc/genesis.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix: linter

- .github/workflows/changelog.yml
- app/upgrades/v4/upgrade.go
- app/upgrades/v4/upgrade_test.go
- x/eibc/genesis.go
- x/rollapp/types/chain_id.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(upstream): upstream fixes to v3.2.0

- x/streamer/keeper/genesis.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(stream): fix genesis export for streams to export all streams not just the active ones

- app/ante/eip712_test.go
- x/incentives/client/cli/query_test.go
- x/rollapp/keeper/msg_server_update_rollapp_test.go
- x/rollapp/keeper/rollapp.go
- x/rollapp/types/genesis_info_test.go
- x/rollapp/types/message_create_rollapp.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollapp): allow tokenless on `CreateRollapp` / `UpdateRollapp` with eip

- .github/workflows/changelog.yml
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(ci): Fix changelog workflow

- .github/workflows/changelog.yml
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(ci): Separete changelog workflow to manually and automatically

- CHANGELOG.md
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(changelog): updated changelog

- x/lockup/keeper/lock.go
- x/rollapp/keeper/sequencer_hooks.go
----
fix some function names in comment
I have...
SDK Checklist
----
For Reviewer:
----
> chore: fix some function names in comment

- x/rollapp/types/genesis.go
- x/rollapp/types/genesis_test.go
----
Closes #1586 
I have...
SDK Checklist
----
For Reviewer:
----
> fix: add missing validations in x/rollapp/types/genesis.go

- x/iro/types/plan.go
- x/rollapp/keeper/msg_server_update_rollapp_test.go
- x/rollapp/types/message_update_rollapp.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(iro): missing `StartTimeAfterSettlement` in IRO default params

- .github/workflows/e2e-test-nightly.yml
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(ci): push e2e test results to a slack channel

- x/eibc/genesis.go
- x/lightclient/client/cli/tx.go
- x/lightclient/module.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(lightclient): Add tx for setting canonical light client

- .github/workflows/e2e-test-nightly.yml
- .github/workflows/e2e_test.yml
- .github/workflows/e2e_test_upgrade.yml
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(ci): bump actions/upload-artifact to v4

- .github/workflows/e2e-test-nightly.yml
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(ci): Add token to secrets inputs

- .github/workflows/e2e-test-nightly.yml
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(ci): try sending report via webhook

- ibctesting/light_client_test.go
- x/lightclient/keeper/canonical_client.go
- x/lightclient/keeper/client_store.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(lightclient): fixed consensus states iterator

- app/ante/eip712_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(eip712): adding utility to print eip712 structs

- app/app.go
- app/apptesting/test_helpers.go
- app/apptesting/test_suite.go
- x/incentives/keeper/gauge_asset.go
- x/sponsorship/module.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(UT): add UT utilities

- x/iro/types/bonding_curve.go
- x/lockup/keeper/lock.go
- x/rollapp/keeper/rollapp.go
make function comment match function name
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore: make function comment match function name

- x/rollapp/keeper/registered_denoms.go
- x/rollapp/keeper/registered_denoms_test.go
----
Closes #1725 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(denommetadata): wrong key in paginated guery for registered denoms

- app/keepers.go
- app/transfer_stack.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> refactor: move init transfer stack

- x/sequencer/keeper/fraud.go
- x/sequencer/keeper/msg_server_create.go
- x/sequencer/keeper/msg_server_update.go
- x/sequencer/keeper/proposer.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix: rename x/sequencer after sentinel func

- app/app.go
- app/upgrades/upgrade.go
- app/upgrades/v5/upgrade.go
- x/sponsorship/keeper/keeper.go
> feat(upgrade): upgrade handler to initialize endorsements for existing rollapps

- x/iro/types/liquidity.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> doc(iro): find equilibrium explain

- app/ante/ante_options.go
- app/ante/ante_test.go
- app/ante/cosmos_handler.go
- app/ante/eth_handler.go
- app/app.go
- app/keepers.go
- app/keys.go
- app/modules.go
- app/upgrades/v5/constants.go
- go.mod
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(app): add circuit breaker module

- x/dymns/keeper/msg_server.go
- x/dymns/keeper/msg_server_complete_sell_order.go
- x/dymns/types/dym_name_test.go
- x/iro/types/liquidity.go
- x/lightclient/keeper/canonical_client.go
fix some typos in comment
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore: fix some typos in comment

- app/params/encoding.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(evm): fix eth custom get signers registry

- app/upgrades/v5/upgrade.go
- x/iro/keeper/migrations.go
----
Closes https://github.com/dymensionxyz/dymension/issues/1829
I have...
SDK Checklist
----
For Reviewer:
----
> upgrade(iro): check validate basic for plans

- x/lockup/keeper/msg_server.go
> fix(lockup): charging LockCreationFee only on new lock creation

- .golangci.yml
- app/upgrades/v5/upgrade.go
- app/upgrades/v5/upgrade_test.go
- x/rollapp/keeper/liveness.go
- x/rollapp/types/liveness.go
> chore(migration): account for faster blocks in rollapp params (dispute + liveness)

- x/lockup/keeper/lock.go
- x/lockup/keeper/msg_server.go
- x/lockup/keeper/msg_server_test.go
- x/lockup/keeper/store.go
> feat(incentives): prevent multiple partial unlocks for a single lock

- proto/dymensionxyz/dymension/iro/events.proto
- x/iro/keeper/claim.go
- x/iro/keeper/trade.go
- x/iro/keeper/trade_test.go
- x/iro/types/events.pb.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(IRO): refactor IRO buy/sell events to return `Coin` instead of `Int`

- x/delayedack/types/codec.go
- x/dymns/types/codec.go
- x/eibc/types/codec.go
- x/incentives/types/codec.go
- x/iro/types/codec.go
- x/lockup/types/codec.go
- x/rollapp/types/codec.go
- x/sequencer/types/codec.go
- x/streamer/types/codec.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(codec): added missing codec registrations

- app/app.go
- app/upgrades/upgrade.go
- app/upgrades/v5/upgrade.go
- app/upgrades/v5/upgrade_test.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(upgrade): wired gas free whitelisted txs

- x/iro/types/liquidity.go
remove redundant word in comment
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore: remove redundant word in comment

- app/keepers.go
…ation.
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(migration): Added missing keytable initialization of ibc keeper

- app/params/encoding.go
- x/sequencer/types/codec.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(sequencer): missing interface registration in sequencer module 

- testutil/math/math.go
- x/iro/types/bonding_curve.go
- x/iro/types/bonding_curve_test.go
- x/iro/types/liquidity_test.go
* fixed a bug in `TokensForExactInAmount`
* fixed a truncation bug in test util `ApproxEqualRatio`
> fix(iro): fixed TokensForExactInAmount with USDC

- ibctesting/eibc_test.go
- x/delayedack/keeper/completion.go
There is a [new function](https://pkg.go.dev/maps@go1.21.1#Copy) added in the go1.21 standard library, which can make the code more concise and easy to read.
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> refactor: use maps.Copy for cleaner map handling

- x/sequencer/keeper/msg_server_bond.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(rollapp): update error message for fork precondition in Unbond method

- x/denommetadata/client/cli/tx.go
- x/denommetadata/client/cli/tx_register_hl.go
- x/denommetadata/keeper/keeper_test.go
- x/denommetadata/keeper/testdata/denom_kas.json
- x/denommetadata/module.go
Because the auto CLI didnt work
> Add manual CLI tx for HL denom meta reg

- app/ante/eip712_test.go
- app/params/encoding.go
- cmd/dymd/cmd/debug.go
- cmd/dymd/cmd/root.go
- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(eip712):  improvements with eip712 support

- app/export.go
- app/keys.go
- testutil/nullify/nullify.go
a allowed -> an allowed
gets existing -> gets the existing
Fill analyze -> Fill analyzes
> chore: fix grammatical issues in code comments

- proto/dymensionxyz/dymension/rollapp/rollapp.proto
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore: fix typo in comment

- x/incentives/keeper/iterator.go
- x/streamer/keeper/suite_test.go
----
Closes https://github.com/dymensionxyz/dymension/issues/1739
I have...
SDK Checklist
----
For Reviewer:
----
> fix(streamer): tests after v50

- x/delayedack/ibc_middleware.go
- x/ibc_completion/ibc_module.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> forward: support both memo types

- x/iro/keeper/migration_test.go
- x/iro/keeper/migrations.go
closes #1999 
On mainnet, IRO plans that passed their eq point, will be auto migrated to an AMM pool
> feat(IRO): migrate iro plans that pass the eq point

- Dockerfile
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(ci): bump go version to 1.24

- app/modules.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(migration): fixed migration order

- x/dymns/keeper/grpc_query_test.go
- x/incentives/README.md
https://github.com/ethereum/go-ethereum/pull/32662
> chore: using testing.B.Loop

- x/bridgingfee/client/cli/tx.go
- x/dymns/utils/dym_name.go
- x/rollapp/types/rollapp.go
- x/sponsorship/client/cli/tx.go
Optimize code using a more modern writing style which can make the code more efficient and cleaner.
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> refactor: replace Split in loops with more efficient SplitSeq

- x/iro/keeper/trade.go
- x/iro/keeper/trade_test.go
Closes https://github.com/dymensionxyz/audits/issues/46
> feat(iro): after purchase, validate remaining tokens are purchasable

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> dep(txfees): coin conversion uses spot price instead of swap estimation

- x/forward/cli/util.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(cli): properly parse recipient flag for IBC forwarding

- app/upgrades/v5/types/dymns/params.go
- x/delayedack/ibc_middleware.go
- x/denommetadata/ibc_middleware.go
- x/dymns/types/buy_offer.go
- x/dymns/types/genesis.go
- x/dymns/types/msg_place_sell_order.go
- x/dymns/types/msg_register_alias.go
- x/dymns/types/msg_register_name.go
- x/dymns/types/msg_update_resolve_address.go
- x/dymns/types/params.go
- x/dymns/types/sell_order.go
- x/iro/keeper/create_plan.go
- x/iro/keeper/params.go
- x/iro/keeper/params_test.go
- x/rollapp/types/chain_id.go
Cherry pick of ef88f236a76c317b2f567295d248e863b118b4e0
> fix: filepath in err string when using Wrapf causes non-determinism
