app/app.go
docs/static/openapi.yml
go.mod

This PR removes the monitoring module from the codebase and SPN as a dependency.
close https://github.com/dymensionxyz/dymension/issues/209

chore: remove the `monitoringp` module

---

app/app.go
app/encoding.go
app/params/encoding.go
app/simulation_test.go
app/test_app.go
cmd/dymd/cmd/config.go
cmd/dymd/cmd/genaccounts.go
cmd/dymd/cmd/root.go
cmd/dymd/main.go
testutil/network/network.go

Migrated `main` and `app` packages from using the deprecated `cosmoscmd`.
close https://github.com/dymensionxyz/dymension/issues/214

chore: remove dependence on `cosmoscmd`

---

x/rollapp/keeper/msg_server_create_rollapp.go
x/rollapp/types/message_create_rollapp.go
x/rollapp/types/message_create_rollapp_test.go

This PR removes the additional check that rollapp-id shouldn't have revision format.
For now, there is no justification for this check.
It conflicts with standard chain-id naming, and introduces IBC dependency to whoever uses the `rollapp` module (e.g dymint)
---
For Author:
---
For Reviewer:
--- 

fix: removed ibc dependency on x/rollapp/types

---

app/ante/ante.go
app/ante/ante_options.go
app/ante/handlers.go
app/app.go
app/params/config.go
app/test_helpers.go
cmd/dymd/cmd/config.go
x/rollapp/keeper/rollapp_suite_test.go

This PR copies the ethermint's Ante handler to the dymension hub
- It's important as we gonna add other modules, and we need the freedom to change the ante handler.
Also clean a bit the testutils in preparation for the AMM module
---
For Author:
---
For Reviewer:
--- 

chore: Adding hub's ante handler instead of using ethermint's

---

x/rollapp/keeper/grpc_query_get_state_info_by_height_test.go

---
For Author:
---
For Reviewer:
---;

chore: UT performance

---

x/rollapp/client/cli/tx_create_rollapp.go
x/rollapp/client/cli/tx_update_state.go
x/sequencer/client/cli/tx_create_sequencer.go
x/streamer/client/cli/tx_create_stream.go
x/streamer/client/cli/tx_replace_distribution.go
x/streamer/client/cli/tx_terminate_stream.go
x/streamer/client/cli/tx_update_distribution.go

The `ValidateBasic` function has been called in the `GenerateOrBroadcastTxWithFactory` function, so we no longer need to add the `ValidateBasic` function when writing Cli. Related PRs can be viewed at: https://github.com/cosmos/cosmos-sdk/pull/9236#discussion_r623803504
---
For Author:
---
For Reviewer:
---;

refactor: Remove ValidateBasic in cli

---

app/ante/handlers.go
app/ante/reject_msgs.go
app/app.go
app/healthcheck.go
cmd/dymd/cmd/inspect_tendermint.go
x/streamer/client/cli/query.go
x/streamer/client/proposal_handler.go
x/streamer/keeper/distribute.go
x/streamer/types/keys.go

----
Closes #XXX
I have...
---
For Reviewer:
---

chore: Audit fixes round 2

---

.github/workflows/release_binary.yml
Dockerfile
docker-compose.yml
scripts/start_localnode.sh

----
I have...
SDK Checklist
---
For Reviewer:
---

CI: Release Binary

---

proto/dymension/eibc/query.proto
x/eibc/client/cli/query.go
x/eibc/client/cli/query_command_orders.go
x/eibc/keeper/grpc_query.go
x/eibc/keeper/grpc_query_test.go
x/eibc/types/query.pb.go
x/eibc/types/query.pb.gw.go

This PR will add query demand orders by status to Dymension
----
Closes #636
I have...
SDK Checklist
----;
For Reviewer:
---;

feat: add Query demand orders by status cmd

---

x/rollapp/keeper/block_height_to_finalization_queue.go
x/rollapp/keeper/block_height_to_finalization_queue_test.go

There is a problem  retrieving pending finalization queues,  that this PR is fixing. The PR includes extra test for pending finalization queues
----
Closes #646 
I have...
SDK Checklist
----;
For Reviewer:
---;

fix: bad state info finalization

---

x/eibc/types/tx.go

----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;

fix: add validation on demand order id max length 

---

app/app.go
ibctesting/rollapp_genesis_token_test.go
scripts/setup_local.sh
scripts/src/genesis_config_commands.sh
testutil/keeper/rollapp.go
utils/ibc.go
x/delayedack/eibc.go
x/rollapp/keeper/keeper.go
x/rollapp/types/expected_keepers.go

----
Closes #671 
I have...
SDK Checklist
----;
For Reviewer:
---;

fix(rollapp): rollapp genesis token not registered as IBC denom

---

app/app.go
ibctesting/delayed_ack_test.go
ibctesting/denom_metadata_test.go
ibctesting/eibc_test.go
ibctesting/utils_test.go
testutil/keeper/delayedack.go
testutil/mockpv/mockpv.go
x/delayedack/ibc_middleware.go
x/delayedack/keeper/keeper.go
x/delayedack/types/errors.go
x/delayedack/types/expected_keepers.go
x/sequencer/types/sequencer.go

----
The  objective of this PR is to prevent potential vector attacks that utilises other cosmos chains with the same chain id of an existing rollappid to enable malicious ibc-transfers to other chains that are not the rollapp itself.
For that, we need to prevent  that any ibc-transfer can use the chain id of an existing rollapp, without coming from the real rollapp, authenticating the rollapp id. In the following we list 3 potential solutions:
Solution 1:  Reject  channels creation with same id of rollapp id
Main drawback: it is not possible to prevent channel creations with the chain id equal to a  rollappid,  that is not yet registered in the hub, but it can be known beforehand by an attacker.
Solution 2:   Reject light clients update for a channel with a rollapp id equal to a …

feat: rollapp ibc state validation upon state update 

---

CHANGELOG.md
app/app.go
go.mod
go.sum

This PR upgrades packet forward middleware to its latest release, fixing a bug. 
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;

fix: update packet forward middleware

---

x/rollapp/keeper/invariants_test.go

This PR fixes a small issue in the invariants test for the rollapp module, which creates a state update with the wrong height, because of a context issue.
----
Closes #690 
I have...
SDK Checklist
----;
For Reviewer:
---;

fix: wrong state update height for invariants test in rollapp module

---

x/sequencer/keeper/msg_server_create_sequencer.go

This PR fixes a potential int overflow in the CreateSequencer(), when casting maxsequencers from uint64 to int 
----
Closes #703 
I have...
SDK Checklist
----;
For Reviewer:
---;

fix: potential int overflow when creating sequencers

---

go.mod

----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;

fix: fix osmo dep version

---

x/rollapp/keeper/msg_server_update_state.go
x/rollapp/keeper/msg_server_update_state_test.go

----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;

fix: accept rollapp initial state with arbitrary height

---

x/sequencer/keeper/msg_server_unbond.go
x/sequencer/keeper/sequencer.go
x/sequencer/keeper/sequencer_suite_test.go
x/sequencer/keeper/sequencer_test.go

when rotating sequencer, choose the next one sorted by bond
----
Closes [#716 ](https://github.com/dymensionxyz/dymension/issues/716)
I have...
SDK Checklist
----;
For Reviewer:
---;

feat(sequencers): sort sequencers by bond when rotating

---

go.mod

Update from non existing toolchain `1.22` to a proper `1.22.0`
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;

update go to an existing toolchain

---

x/eibc/keeper/hooks.go
x/eibc/keeper/hooks_test.go

Closes [#760](https://github.com/dymensionxyz/dymension/issues/760)
This PR will refactor logic of AfterPacketDeleted and make UnderlyingPacketExistInvariant won't break incase sequencer submitted a fraudulent state. Also added refactor and added testcase for this.
I have...
SDK Checklist
----;
For Reviewer:
---;

fix(eibc): Remove reverted packet to ensure UnderlyingPacketExistInvariant

---

app/app.go
x/common/types/address.go

----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;

fix(account): fixed wrong bech32 prefix for accountKeeper

---

ibctesting/eibc_test.go
x/delayedack/eibc.go

This is a simpler/more surgical version of https://github.com/dymensionxyz/dymension/pull/800/files
----
Closes https://github.com/dymensionxyz/dymension/issues/799
I have...
SDK Checklist
----;
For Reviewer:
---;

fix(delayedack): do not create eibc order on timeout/errack if fee is not positive

---

x/delayedack/ibc_middleware.go
x/delayedack/keeper/fraud.go
x/delayedack/keeper/fraud_test.go
x/delayedack/keeper/hooks_test.go
x/delayedack/keeper/invariants_test.go
x/delayedack/rollapp_hooks.go

covering few scenarios:
* hub -> Rollapp: delayed acknowledgement reverted
* hub -> Rollapp: delayed timeout reverted
for both cases, refund needed.
regarding the rollapp->hub (delayed onRecv), no need to handle it, as the original packet commitment won't be present on the forked rollapp
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;

fix(fraud): refunding pending outgoing packets

---

x/common/types/rollapp_packet.go
x/delayedack/rollapp_hooks.go
x/rollapp/keeper/msg_server.go

----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;

fix(delayedack): acknowledgement not written in case of ackerr

---

x/rollapp/keeper/invariants.go

This PR is aimed at fixing an issue with the block-height-to-finalization-queue invariant, that tries to find non-finalized state infos in the blockheighttofinalization queue, but it shouldn't for frozen rollapps.
----
Closes #820 
I have...
SDK Checklist
----;
For Reviewer:
---;

fix (rollapp): invariant block-height-to-finalization-queue fix for freezing rollapp

---

.github/workflows/golangci_lint.yml
.golangci.yml

----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;

fix(code standards): bring over more linters from dymint repo

---

Dockerfile

https://stackoverflow.com/questions/64874133/what-does-run-apk-add-no-cache-tree-mean-in-a-dockerfile

chore(ci): don't cache installed packages in runtime image

---

ibctesting/delayed_ack_test.go
x/eibc/keeper/keeper_test.go
x/rollapp/keeper/invariants.go
x/sequencer/keeper/slashing.go

fix some comments
----
Closes #XXX
I have...
SDK Checklist
----;
For Reviewer:
---;

chore: fix some comments

---

x/incentives/README.md

This PR corrects a typo in the `x/incentives/README.md` where the word "the" was repeated in the description of non-perpetual gauges.
----
I have...
SDK Checklist
----;
For Reviewer:
---;

chore(readme): repeated word in x/incentives README

---

x/rollapp/keeper/grpc_query_rollapp_test.go
x/rollapp/keeper/liveness_test.go
x/rollapp/keeper/rollapp_suite_test.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix: tests that run unwanted

---

x/lightclient/ante/ibc_msg_update_client.go
x/lightclient/ante/ibc_msg_update_client_test.go

----
Closes #https://github.com/dymensionxyz/dymension/issues/1211
I have...
SDK Checklist
----
For Reviewer:
----

fix(light client): adds tests and check to disable misbehavior update for canon client

---

x/denommetadata/ibc_middleware.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(denommetadata): correct base denom format

---

readme.md

> [!NOTE]  
> Corrected a typo in the "Checking rewards" section where "outpup" was replaced with "output" in the script comment for watching the incentives gauge output.

Fix typos readme.md

---

x/sponsorship/types/genesis.go
x/sponsorship/types/genesis_test.go

----
Closes #1269 
I have...
SDK Checklist
----
For Reviewer:
----

fix(sponsorship): missing duplicate vote validation in GenesisState

---

x/rollapp/types/message_create_rollapp_test.go
x/rollapp/types/rollapp.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(rollapp): fix validation of empty genesis info

---

x/dymns/client/cli/tx_update_resolve_address.go
x/lockup/keeper/grpc_query.go
x/lockup/keeper/lock.go
x/lockup/keeper/msg_server.go
x/lockup/keeper/store.go
x/lockup/types/msgs.go
x/sequencer/keeper/rotation.go

`Wrap` and `Wrapf` functionality has been moved to it's own module: "cosmossdk.io/errors".
Modified instances of `Wrap` and `Wrapf` to use "cosmossdk.io/errors" instead.
See: https://github.com/cosmos/cosmos-sdk/blob/v0.47.13/types/errors/errors.go#L7-L27
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

chore: replace deprecated `Wrap` and `Wrapf`

---

app/keepers/keepers.go
x/sponsorship/keeper/keeper.go
x/sponsorship/keeper/votes.go
x/sponsorship/keeper/votes_test.go
x/sponsorship/types/expected_keepers.go

----
Closes #1264 
I have...
SDK Checklist
----
For Reviewer:
----

feat(sponsorship): only allow sponsoring rollapps with bonded sequencers

---

x/rollapp/types/message_update_rollapp.go
x/rollapp/types/message_update_rollapp_test.go

Currently owner address is not validated in MsgUpdateRollappInformation's ValidateBasic. This commit adds a check to ensure that the owner is a bech32-encoded address.
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(rollapp): validate owner address

---

proto/dymensionxyz/dymension/rollapp/rollapp.proto
x/rollapp/types/rollapp.pb.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(doc): improve docstring on proto rollapp LivenessEventHeight

---

x/denommetadata/module.go
x/rollapp/genesisbridge/ibc_module.go
x/vfc/hooks/denom_metadata_hooks.go
x/vfc/hooks/denom_metadata_hooks_test.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(iro): removed ibc filter for VFC creation

---

x/sequencer/keeper/invariants.go
x/sequencer/keeper/msg_server_create_sequencer.go
x/sequencer/keeper/msg_server_create_sequencer_test.go
x/sequencer/keeper/msg_server_increase_bond.go
x/sequencer/keeper/unbond.go
x/sequencer/types/msg_create_sequencer.go
x/sequencer/types/params.go

----
Closes #1291 
This PR does the following:
* better enforcement of single denom for sequencer bond 
* requires `MinBond` param to be > 0 (instead >= 0 currently)

fix(sequencers): incorrect sorting mechanism allows manipulation of proposer selection

---

x/lightclient/keeper/canonical_client.go
x/lightclient/types/state.go
x/lightclient/types/state_test.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

feat(ibc): add debug log and reason when client fails to be made canonical

---

x/lightclient/keeper/hook_listener.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(lightclient): make sure to prune signers when setting canonical client for first time

---

x/rollapp/keeper/grpc_query_state_info.go

When querying state info by height is returning an error different from ErrNotFound and dymint does not recognize it and retries querying when not necessary.
----
Closes #1396 
I have...
SDK Checklist
----
For Reviewer:
----

fix(rollapp): replace not found error to be detected by dymint

---

app/keepers/keepers.go
scripts/src/genesis_config_commands.sh
x/delayedack/client/cli/query.go

`crisisKeeper` gets `nil` `bankKeeper`
which makes it panic when handling invariant

fix(crisis): Fix crisis module wiring

---

Contributing.md

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

chore(doc): contributing don't care about first word of docstring

---

x/lightclient/keeper/hook_listener.go
x/lightclient/keeper/hook_listener_test.go
x/lightclient/keeper/keeper.go

Solves arts testnet issue
```
Nov 11 15:09:41 ip-10-0-2-46 rollapp-evm[12691]: time="2024-11-11T15:09:41Z" level=error msg="Submit batch[startHeight 776661 endHeight 0x2aee4e0 error broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: hook: after update state: validate optimistic: got cons state but no signer addr: client: 07-tendermint-44: h: 776660: internal [cosmossdk.io/errors@v1.0.1/errors.go:155] With gas wanted: '18446744073709551615' and gas used: '443375' : unknown request]" module=settlement_client
```
We shouldn't expect light client signers for consensus states from pre upgrade rollapps.
This PR just makes the file the same as it is in https://github.com/dymensionxyz/dymension/pull/1354, which also fixes …

fix(lightclient): don't expect signer

---

app/ante/handlers.go
app/ante/reject_msgs.go
app/ante/reject_msgs_test.go
x/lightclient/ante/ibc_msg_update_client.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

feat(ante): allow rejection based on depth

---

app/keepers/keepers.go
x/denommetadata/ibc_middleware.go
x/denommetadata/ibc_middleware_test.go
x/denommetadata/keeper/keeper.go
x/denommetadata/keeper/rollback.go
x/denommetadata/types/expected_keepers.go
x/rollapp/keeper/registered_denoms.go
x/rollapp/keeper/sequencer_hooks.go
x/sequencer/keeper/bond.go
x/sequencer/keeper/fraud.go
x/sequencer/keeper/fraud_test.go
x/sequencer/keeper/msg_server_create.go
x/sequencer/keeper/msg_server_update.go
x/sequencer/keeper/proposer.go
x/sequencer/keeper/rotation.go
x/sequencer/keeper/rotation_test.go
x/sequencer/types/expected_keepers.go
x/sequencer/types/hooks.go

feat(sequencer): hardforking when rotating to sentinel

---

x/rollapp/keeper/hard_fork.go
x/rollapp/keeper/sequencer_hooks.go
x/sequencer/keeper/proposer.go
x/sequencer/keeper/rotation.go
x/sequencer/types/hooks.go

- make sure to clear liveness events on hard fork (since sequencer will not be available)
- make sure to start liveness events and set nextProposer whenever a real proposer is chosen
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(rollapp,sequencer): rotation and liveness slash - hook onto all real sequencer changes

---

x/sponsorship/types/types.go
x/sponsorship/types/types_test.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(sponsorship): remove negative weights from distribution

---

x/sponsorship/keeper/hooks.go
x/sponsorship/keeper/keeper_test.go
x/sponsorship/keeper/msg_server.go
x/sponsorship/keeper/votes.go

… power
- Removed redundant ceiling while calculating staking power
- Reordered events, so now they are more transparent
- Fixed incorrect field in `EventVotingPowerUpdate` when the vote is removed
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(sponsorship): removed redundant ceiling while calculating staking power

---

x/iro/keeper/invariants.go
x/iro/keeper/iro.go

It's not a very interesting invariant but nvm
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(iro): last plan id invariant fix

---

app/keepers/keepers.go
x/bridgingfee/ibc_module.go

closes #1554 
* refactor charging fee implementation
* charging fees in cacheCtx to allow clean failure

fix(bridging_fee): adding cacheCtx for charging fees

---

x/lightclient/README.md

This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `useable` to `usable`
Corrected `info's` to `infos`
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

app/keepers/keepers.go
x/delayedack/ibc_middleware.go
x/delayedack/keeper/finalize.go
x/denommetadata/ibc_middleware.go
x/denommetadata/ibc_middleware_test.go
x/denommetadata/types/expected_keepers.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(IBC): remove denom registration fees. validate OnRecvPacket initially

---

app/genesis.go
x/common/types/packet_uid.go
x/lightclient/types/params.go
x/lockup/keeper/msg_server.go
x/rollapp/keeper/sequencer_hooks.go

This PR corrects minor typos in comments across various files to enhance clarity and maintain consistency in the codebase documentation.
---
1. **app/genesis.go**  
- Fixed "key'd by a identifier string" to "key'd by an identifier string."
2. **x/common/types/packet_uid.go**  
- Corrected "an Rollapp IBC packet" to "a Rollapp IBC packet."
3. **x/lightclient/types/params.go**  
- Updated "calculates an sensible trust period" to "calculates a sensible trust period."
4. **x/lockup/keeper/msg_server.go**  
- Improved clarity by changing "defense in depth, double checking" to "defense in depth, double-checking."
5. **x/rollapp/keeper/sequencer_hooks.go**  
- Fixed "proposer for an halted rollapp" to "proposer for a halted rollapp."

Fix minor typos

---

x/eibc/genesis.go
x/eibc/genesis_test.go

----
Closes #1576 
I have...
SDK Checklist
----
For Reviewer:
----

fix malformed tracking_packet_key by ensuring base64 encoding/decoding during Genesis export/import

---

app/keepers/keepers.go
app/keepers/modules.go
app/upgrades/v4/upgrade.go
x/sponsorship/types/params.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(upgrade): moved old params load to common flow instead of upgrade specific

---

x/dymns/client/cli/tx_bid_alias.go

This PR fixes grammatical errors in the CLI command `tx_bid_alias.go` where the indefinite article "a" was incorrectly used before words starting with a vowel sound ("Alias"). 
The changes ensure proper usage of "an" for better readability and compliance with grammar standards.
---
- Corrected two instances of "a Alias" to "an Alias" in:
- Function documentation.
- The `Short` description of the CLI command.
---
---
---

fix: correct usage of indefinite articles

---

app/keepers/keepers.go
ibctesting/light_client_test.go
x/incentives/keeper/msg_server_test.go
x/lockup/client/cli/query.go
x/lockup/keeper/lock.go
x/sequencer/keeper/get_and_set.go
x/sponsorship/types/types.go

fix some typos in comment
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

chore: fix some typos in comment

---

x/iro/keeper/trade.go
x/iro/types/bonding_curve.go

currently, when selling IRO tokens, the user is first charged with the taker fee, and than sell it's tokens.
It can cause to failures in case the user doesn't have enough funds to pay the fee.
This PR fixes it, so the taker fee charged **AFTER** the sell outcome

fix(iro): first sell tokens, than charge fee

---

Contributing.md

- `seperated` → `separated`
- `programatically` → `programmatically`
- `readabilty` → `readability`
- `Ubiquitious` → `Ubiquitous`
- `Utilies` → `Utilities`

Fix spelling errors in Contributing.md

---

x/lockup/README.md
x/rollapp/keeper/fraud_proposal.go

1. Fixed error logging format in `x/rollapp/keeper/fraud_proposal.go` by replacing:
ctx.Logger().Error("Fraud proposal.", err)  -->  ctx.Logger().Error("Fraud proposal", "error", err)
2. Minor fix was made in the **README.md** of the `lockup` module to correct an incorrect reference to the "Concepts" section

Fix error logging format in fraud proposal handler

---

.github/workflows/codeql.yml
.github/workflows/label-internal-pr.yml
.github/workflows/release_docker_images.yml
.github/workflows/update_docker_images.yml

Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected

ci: bump actions/checkout to v4

---

.github/workflows/golangci_lint.yml
.golangci.yml

Guys update to v2
Some stuff removed, because rolled into staticheck or supported by default

chore: bump golangci yaml to v2

---

app/upgrades/v5/upgrade.go
x/sponsorship/types/types.go
x/streamer/keeper/hooks.go

We need to carefully fill the `TotalShare` setting of endorsements for existing RAs. To do so, we iterate through the distribution gauges and check theirs total voting power. It might be zero if no one endorsed the RA. `TotalShare` equals to the total voting power cast to the RA.
Closes https://github.com/dymensionxyz/audits/issues/32

fix(sponsorship): missing total power in the endorsement migration

---

proto/dymensionxyz/dymension/common/completion_hook.proto
proto/dymensionxyz/dymension/incentives/genesis.proto

Title:  
Fix Typos in Proto Comments ("fulfillment" and "receive")
Description:  
This pull request corrects two typographical errors in proto files:
- In completion_hook.proto, "fulfillment" was misspelled as "fulfillment".
- In genesis.proto, "receive" was misspelled as "recieve".
These changes improve code documentation clarity and maintain consistency. No functional code changes are included.

Fix Typos in Proto Comments 

---

app/ante/cosmos_handler.go
app/ante/eip712_test.go

This PR fixes small grammar issues across two files:
In cosmos_handler.go, corrected the passive form from not suppose to be used to not supposed to be used.
In eip712_test.go, replaced incorrect phrase "could not be casted" with the correct "could not be cast".

Fix minor grammar issues in comments and test assertions

---

go.mod
go.sum

Update deps to include the following:
https://github.com/dymensionxyz/ibc-go-fork/compare/v8.7.0...dymensionxyz:ibc-go-fork:mainnet_simulation_beyond?expand=1

updated deps for ibc-go fork

---

proto/dymensionxyz/dymension/incentives/params.proto
proto/dymensionxyz/dymension/incentives/query.proto

This PR fixes minor spelling mistakes in proto documentation comments:
- Corrected `wether` to `whether`.
- Corrected `recieve` to `receive`.
These changes improve the clarity and professionalism of the code documentation.  No logic or functionality is affected.

chore: fix misspelling issues

---

x/lockup/README.md

This PR updates the Table of Contents in `x/lockup/README.md` to ensure all links accurately point to the correct sections:
- Fixed anchor from `Keeper` to `Keepers`
- Fixed anchor from `Params` to `Parameters`
- All other TOC entries were checked and aligned with their actual section headings
No logic or functionality is affected.

docs(lockup): update TOC anchors in README.md

---

readme.md

- **Before:** `dymint/actions/workflows/lint.yml` (404 error)
- **After:** `roller/actions/workflows/lint.yml` (working badge)
The original badge was pointing to a non-existent workflow in the dymint repository. Updated to use the correct roller repository workflow.

fix: Update dymint lint badge to use correct workflow

---

x/forward/hyperlane.go
x/incentives/keeper/export_test.go

Corrected typo in comment in x/forward/hyperlane.go: fixed "responsse" to "response".
Fixed parameter name typo in x/incentives/keeper/export_test.go from guageID to gaugeID in DeleteGaugeRefByKey method.
Fixed typo in comment for MoveUpcomingGaugeToActiveGauge method: changed "it's" to "its".

chore: Fix typos and parameter naming in incentives and forward modules

---

.github/workflows/changelog.yml
.github/workflows/codeql.yml
.github/workflows/e2e-test-nightly.yml
.github/workflows/e2e_test.yml
.github/workflows/e2e_test_upgrade.yml
.github/workflows/golangci_lint.yml
.github/workflows/label-internal-pr.yml
.github/workflows/markdown_lint.yml
.github/workflows/proto.yaml
.github/workflows/release_binary.yml
.github/workflows/release_docker_images.yml
.github/workflows/test.yml
.github/workflows/update_docker_images.yml

Maintenance update to actions/checkout@v5 to align with the current runner stack (Node 24); nothing else modified.
Release notes: https://github.com/actions/checkout/releases/tag/v5.0.0

chore(ci): upgrade checkout to v5

---

x/denommetadata/keeper/msg_server.go

fix inconsistent function name in comment
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

chore: fix inconsistent function name in comment

---

utils/uinv/funcs.go
x/common/types/rollapp_packet.go

Fix incorrect error message in RollappPacket.ValidateBasic() method.
The validation checks for empty relayer but returns "status cannot be empty" 
error message. Updated to return "relayer cannot be empty" to match the 
actual validation logic.
also fixed typo

fix: correct error message for relayer validation in RollappPacket

---

Dockerfile.debug
Makefile

Align Go version across build surfaces to 1.24:
- Dockerfile.debug: golang:1.23 → golang:1.24 (alpine3.21)
- Makefile: GOLANG_CROSS_VERSION v1.22 → v1.24
- go.mod already declares go 1.24.6; main Dockerfile already uses golang:1.24

Go version alignment

---

scripts/protoswagfix/main.go

Starting from Go 1.16, some functions in the ioutil package have been deprecated. The Go team recommends quickly switching to methods from the os or io packages instead. 
More info can see: https://github.com/golang/go/issues/45557
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

refactor: replace the deprecated function in the ioutil package
